#!/bin/bash

stack ghci --no-load --no-docker \
      --resolver lts-14.3 \
      --package classy-prelude \
      --package aeson \
      --package clock \
      --package containers \
      --package lens \
      --package mono-traversable \
      --package time \
      --ghci-options -XConstraintKinds \
      --ghci-options -XDataKinds \
      --ghci-options -XDeriveDataTypeable \
      --ghci-options -XDeriveGeneric \
      --ghci-options -XEmptyDataDecls \
      --ghci-options -XFlexibleInstances \
      --ghci-options -XGADTs \
      --ghci-options -XGeneralizedNewtypeDeriving \
      --ghci-options -XLambdaCase \
      --ghci-options -XMultiParamTypeClasses \
      --ghci-options -XMultiWayIf \
      --ghci-options -XNamedFieldPuns \
      --ghci-options -XNoImplicitPrelude \
      --ghci-options -XNoMonomorphismRestriction \
      --ghci-options -XOverloadedStrings \
      --ghci-options -XPackageImports \
      --ghci-options -XPolyKinds \
      --ghci-options -XQuasiQuotes \
      --ghci-options -XRecordWildCards \
      --ghci-options -XScopedTypeVariables \
      --ghci-options -XStandaloneDeriving \
      --ghci-options -XTemplateHaskell \
      --ghci-options -XTupleSections \
      --ghci-options -XTypeFamilies \
      --ghci-options -XTypeOperators \
      --ghci-options -XViewPatterns
