# configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
zstyle :compinstall filename '/home/dan/.zshrc'

autoload -Uz compinit
compinit

ZSH_THEME="robbyrussell"

plugins=(
  git
)

export DISABLE_AUTO_TITLE="true"
precmd() {
  print -Pn "\e]0;%n@%m: %~\a"
}

start-agent() {
  if [ -z $SSH_AUTH_SOCK ]; then
    eval `ssh-agent -s` > /dev/null
  fi
  if [ -z $SSH_AGENT_PID ] && [ -z $SSH_TTY ]; then
    ssh-add ~/.ssh/id_rsa
  fi
}

alias ssh-tunnel="ssh -fN"

start-agent
