
eval "$(/opt/homebrew/bin/brew shellenv)"


# Added by Toolbox App
export PATH="$PATH:/Users/dan/Library/Application Support/JetBrains/Toolbox/scripts"


# >>> coursier install directory >>>
export PATH="$PATH:/Users/dan/Library/Application Support/Coursier/bin"
# <<< coursier install directory <<<


# >>> JVM installed by coursier >>>
export JAVA_HOME="/Users/dan/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.4.1%252B1/OpenJDK25U-jdk_aarch64_mac_hotspot_25.0.4.1_1.tar.gz/jdk-25.0.4.1+1/Contents/Home"
# <<< JVM installed by coursier <<<
